package com.Api.with.h2.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.stereotype.Service;

@Setter
@Entity
@Table (name = "books")

public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//id is automatically generated by the database
    private Long id;
    @NotBlank(message = "Name is mandatory")
    @Size(min = 2, max = 30, message = "Name must be between 2 and 30 characters")
    private String name;
    public static Long counter=1L;
    //private Double price;

    public Book() {
    }

    public Book(String name, Long id, Double price) {
        this.name = name;
        this.id = id;
      //  this.price = price;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

//    public Double getPrice() {
//        return price;
//    }
//
//    public void setPrice(Double price) {
//        this.price = price;
//    }
}
